rbac:
  enabled: true

ingress:
  enabled: false

serviceType: LoadBalancer

user:
  username: "root"
  email: "root@polyaxon.local"
  password: "kaldi"

postgresql:
  persistence:
    enabled: true
    existingClaim: "polyaxon-pvc"

persistence:
  data:
    common-voice:
      mountPath: "/data/common-voice"
      existingClaim: "common-voice-pvc"
    shared-task:
      mountPath: "/data/shared-task"
      existingClaim: "shared-task-pvc"
    data:
      mountPath: "/data/random-data"
      existingClaim: "random-data-pvc"      

